DROP DATABASE IF EXISTS example_0000;
CREATE DATABASE example_0000 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_unicode_ci;
GRANT ALL PRIVILEGES ON example_0000.* TO 'example'@'%' IDENTIFIED BY 'example';
